In [2]:
import numpy as np

docs = ['go india',
       'india india',
       'hip hip hurray',
       'jeetega bhai jeetega india jeetega',
       'bharat mata ki jai',
       'kohli kohli',
       'sachin sachin',
       'inquilab zindabad']

In [3]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='chaitanya')

In [4]:
tokenizer.fit_on_texts(docs)

In [5]:
tokenizer.word_index

{'chaitanya': 1,
 'india': 2,
 'jeetega': 3,
 'hip': 4,
 'kohli': 5,
 'sachin': 6,
 'go': 7,
 'hurray': 8,
 'bhai': 9,
 'bharat': 10,
 'mata': 11,
 'ki': 12,
 'jai': 13,
 'inquilab': 14,
 'zindabad': 15}

In [6]:
tokenizer.word_counts

OrderedDict([('go', 1),
             ('india', 4),
             ('hip', 2),
             ('hurray', 1),
             ('jeetega', 3),
             ('bhai', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 1),
             ('jai', 1),
             ('kohli', 2),
             ('sachin', 2),
             ('inquilab', 1),
             ('zindabad', 1)])

In [7]:
tokenizer.document_count

8

In [8]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[7, 2],
 [2, 2],
 [4, 4, 8],
 [3, 9, 3, 2, 3],
 [10, 11, 12, 13],
 [5, 5],
 [6, 6],
 [14, 15]]

In [9]:
from keras.utils import pad_sequences

In [10]:
sequences = pad_sequences(sequences, padding = 'post')

In [11]:
sequences

array([[ 7,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 4,  4,  8,  0,  0],
       [ 3,  9,  3,  2,  3],
       [10, 11, 12, 13,  0],
       [ 5,  5,  0,  0,  0],
       [ 6,  6,  0,  0,  0],
       [14, 15,  0,  0,  0]])

In [14]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense, SimpleRNN, Embedding, Flatten
from keras.utils import pad_sequences

In [15]:
model = Sequential()
model.add(Embedding(17,output_dim = 2, input_length = 5))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 5, 2)              34        
                                                                 
Total params: 34 (136.00 Byte)
Trainable params: 34 (136.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
model.compile('adam', 'accuracy')

In [17]:
pred = model.predict(sequences)
print(pred)

1/1 [==============================] - 0s 65ms/step
[[[ 0.04498668  0.02575369]
  [ 0.01004316  0.00441178]
  [-0.04520781  0.04828769]
  [-0.04520781  0.04828769]
  [-0.04520781  0.04828769]]

 [[ 0.01004316  0.00441178]
  [ 0.01004316  0.00441178]
  [-0.04520781  0.04828769]
  [-0.04520781  0.04828769]
  [-0.04520781  0.04828769]]

 [[-0.02506527  0.00038903]
  [-0.02506527  0.00038903]
  [ 0.0094241  -0.04519266]
  [-0.04520781  0.04828769]
  [-0.04520781  0.04828769]]

 [[-0.00171446  0.02350128]
  [-0.04090134 -0.04267731]
  [-0.00171446  0.02350128]
  [ 0.01004316  0.00441178]
  [-0.00171446  0.02350128]]

 [[ 0.00445519 -0.01992144]
  [-0.03995708 -0.03087776]
  [-0.0230817  -0.04495019]
  [-0.02518973 -0.03361598]
  [-0.04520781  0.04828769]]

 [[ 0.00647942  0.04562363]
  [ 0.00647942  0.04562363]
  [-0.04520781  0.04828769]
  [-0.04520781  0.04828769]
  [-0.04520781  0.04828769]]

 [[-0.02985091 -0.02709441]
  [-0.02985091 -0.02709441]
  [-0.04520781  0.04828769]
  [-0.045207